---
title: "Reproducible Research Course Project 1"
author: "BJ Kim"
date: "October 7th, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1: Reading in the dataset and manipulating it

```{r reading in the dataset}
data <- read.csv ("activity.csv", header=TRUE)
data$date <- as.Date (data$date)
```

## Step 2A: Histogram of the total number of steps taken each day

```{r Histogram}
Step <- aggregate (steps ~ date, data=data, sum, na.rm=TRUE)
hist (Step$steps, breaks=10, main = "Total number of steps taken per day", xlab = "steps", ylab = "frequencies")
```

## Step 2B: mean and median of steps

```{r mean and median}
StepsMean <- mean (data$steps, na.rm=TRUE)
StepsMedian <- median (data$steps, na.rm=TRUE)

print (paste ("Mean value of steps per day is: ", StepsMean))
print (paste ("Median value of steps per day is: ", StepsMedian))
```

## Step 3: Daily activity pattern

```{r time series plot across all day}
StepsInterval <- aggregate (steps ~ interval, data=data, mean, na.rm=TRUE)
plot (StepsInterval$interval, StepsInterval$steps, type = "l", 
      main = "Average Steps per Five-Minute Interval Across All Day", 
      xlab = "Interval", ylab = "Number of Steps")

MaxStep <- max(StepsInterval$steps)
print (paste ("The maximal number of steps in a five-minute interval is: ", MaxStep))
```


## Step 4: Imputing missing values

```{r missing values}
# basic statistics about missingness
SumMissing <- sum (is.na(data$steps))
print (paste ("The number of missing values in steps is :", SumMissing))

# Imputing median value into missingness
ImputedData <- data
ImputedData$steps[is.na(ImputedData$steps)] <- median(data$steps, na.rm=TRUE)

ImputedStep <- aggregate (steps ~ date, data=ImputedData, sum, na.rm=TRUE)
hist (ImputedStep$steps, breaks=10, 
      main = "Total number of steps taken per day (Imputed dataset)", 
      xlab = "steps", ylab = "frequencies")

ImputedStepsMean <- mean (ImputedData$steps, na.rm=TRUE)
ImputedStepsMedian <- median (ImputedData$steps, na.rm=TRUE)

print (paste ("Mean value of steps per day (imputed dataset) is: ", ImputedStepsMean))
print (paste ("Median value of steps per day (imputed dataset) is: ", ImputedStepsMedian))

```

## Step 5: Differences between weekdays and weekend (using imputed dataset)

```{r weekday versus weekend}

# assigning weekday and weekend
ImputedData$Day <- weekdays(ImputedData$date)
ImputedData$Weekend <- as.factor (ifelse(ImputedData$Day == "토요일" | ImputedData$Day == "일요일", "weekend", "weekday"))

# plotting
library (lattice)
plotting <- aggregate (steps~interval + Weekend, ImputedData, mean)
xyplot (steps~interval | factor (Weekend), data=plotting, aspect = 1/3, type="l")
```


